/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    CompanyHeader: typeof import('./src/components/CompanyHeader.vue')['default']
    CompetitionTable: typeof import('./src/components/CompetitionTable.vue')['default']
    CompetitorAnalysis: typeof import('./src/components/CompetitorAnalysis.vue')['default']
    EBM_index: typeof import('./src/components/EBM_index.vue')['default']
    EbmFormula: typeof import('./src/components/EbmFormula.vue')['default']
    EbmIndex: typeof import('./src/components/EbmIndex.vue')['default']
    EBMIndex: typeof import('./src/components/EBMIndex.vue')['default']
    EbmRanking: typeof import('./src/components/EbmRanking.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GoodContent: typeof import('./src/components/GoodContent.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MainTable: typeof import('./src/components/MainTable.vue')['default']
    MetricCard: typeof import('./src/components/MetricCard.vue')['default']
    OrfanizeFooter: typeof import('./src/components/OrfanizeFooter.vue')['default']
    OrganizeFooter: typeof import('./src/components/OrganizeFooter.vue')['default']
    OrganizeHeader: typeof import('./src/components/OrganizeHeader.vue')['default']
    RankIndex: typeof import('./src/components/RankIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsPanel: typeof import('./src/components/StatisticsPanel.vue')['default']
    TableIndex: typeof import('./src/components/TableIndex.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
